### ISSUE TITLE
SDL Error

### ISSUE THREAD

**Issue by Nazariglez** [gen2brain/go-sdl2-android-example#1]
Hi! I just tried the apk provided in the readme, and I get the error: "Error: dlopen failed: library "./obj/local/arm64-v8a/libexample.so" not found"

Do you know how can I fix this? Thanks

**Comment by gen2brain** [comment]
Yes, you should add soname to library, like this: -ldflags="-s -w -extldflags=-Wl,-soname,libexample.so" , and after that there is no more ./obj/local/

**Comment by gen2brain** [comment]
So apk available for download can show that error on some devices, on some it is ok, not sure why. If you rebuild example with soname (should be changed in mklib.bash) it will work on all devices.
I will rebuild example when I find time.

**Comment by Nazariglez** [comment]
Thanks @gen2brain I will try again with your tip!
